const IMAGES = {
    clear : require('../img/weather-icons/clear.svg').default,
    cloudy : require('../img/weather-icons/cloudy.svg').default,
    drizzle : require('../img/weather-icons/drizzle.svg').default,
    fog : require('../img/weather-icons/fog.svg').default,
    mostlycloudy : require('../img/weather-icons/mostlycloudy.svg').default,
    partlycloudy : require('../img/weather-icons/partlycloudy.svg').default,
    rain : require('../img/weather-icons/rain.svg').default,
    snow : require('../img/weather-icons/snow.svg').default,
    storm : require('../img/weather-icons/storm.svg').default,
    unknown : require('../img/weather-icons/unknown.svg').default,
    
}


export default IMAGES;